server.port: 8082

spring:
    profiles:
        active: dev
    application.name: folklore-service
    # DB properties
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: none
    liquibase.change-log: classpath:db/changelog/changelog-master.xml
---
spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
        username: sa
        password:
    h2:
        console:
            path: /h2-console
            enabled: true
        settings:
            web-allow-others: true
    config.activate.on-profile: dev
    liquibase.change-log: classpath:db/changelog/changelog-master-dev.xml