server.port: ${PORT:8080}
settings.cors_origin: ${CORS_ORIGINS:*}
spring:
    application.name: folklore-service
    # DB properties
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: validate
    liquibase.change-log: classpath:db/changelog/changelog-master.xml
---
spring:
    config.activate.on-profile: dev
    liquibase.change-log: classpath:db/changelog/changelog-master-dev.xml