server.port: ${PORT}
spring:
    application.name: folklore-service
    # DB properties
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: validate
    liquibase.change-log: classpath:db/changelog/changelog-master.xml
springfox.documentation.swagger.v2.path: /api/v2/api-docs
springdoc.documentation.swagger-ui.base-url: /api
---
spring:
    config.activate.on-profile: dev
    liquibase.change-log: classpath:db/changelog/changelog-master-dev.xml