server.port: ${PORT}
# Activity properties
activity.status.rate: 300000
settings.cors_origin: ${CORS_ORIGINS:*}
spring:
    application.name: folklore-service
    # DB properties
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: validate
    liquibase:
        contexts: prod
        change-log: classpath:db/changelog/changelog-master.xml
    jackson:
        default-property-inclusion: non_null
springfox.documentation.swagger.v2.path: /api/v2/api-docs
---
spring:
    config:
        activate:
            on-profile: dev
    liquibase:
        contexts: dev
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
activity.status.rate: 30000
---
spring:
    config:
        activate:
            on-profile: test
    liquibase:
        contexts: test