server:
    port: 8080
spring:
    config.activate.on-profile: romzes
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/folklore
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: none
    h2:
        console:
            enabled: false
    liquibase:
        contexts: romzes,dev